# Generated by Django 5.2.7 on 2025-10-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="driver",
            name="licence_number",
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
