# Generated by Django 5.2.7 on 2025-10-22 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_driver_options_alter_driver_licence_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="licence_number",
            new_name="license_number",
        ),
    ]
